name: Security Scan

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            ref: ${{ github.head_ref }}

        - name: VulnGuard Scan
          uses: DakshRocks21/VulnGuard@main
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BASE_SHA: ${{ github.event.pull_request.base.sha }}
            HEAD_SHA: ${{ github.event.pull_request.head.sha }}
