name: Security Scan

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Debug
          run: |
            ls -la
            ls -la /
            pwd

        - name: VulnGuard Scan
          uses: DakshRocks21/VulnGuard@main
