name: Security Scan

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: VulnGuard Scan
          uses: DakshRocks21/VulnGuard@main
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: VulnGuard Scan
          uses: DakshRocks21/VulnGuard@main
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Debug
          run: |
            ls -la
            ls -la /
            pwd
